version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python Search/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=Search_db
      - POSTGRES_USER=Search_user
      - POSTGRES_PASSWORD=Search_password